const SalesChartData = [
  {
    Income: 59,
    Visitors: 57,
    CompletedOrders: 86,
    PendingOrders: 21,
    month: "Jan",
  },
  {
    Income: 50,
    Visitors: 52,
    CompletedOrders: 78,
    PendingOrders: 28,
    month: "Feb",
  },
  {
    Income: 47,
    Visitors: 53,
    CompletedOrders: 106,
    PendingOrders: 41,
    month: "Mar",
  },
  {
    Income: 54,
    Visitors: 56,
    CompletedOrders: 92,
    PendingOrders: 73,
    month: "Apr",
  },
  {
    Income: 57,
    Visitors: 69,
    CompletedOrders: 92,
    PendingOrders: 99,
    month: "May",
  },
  {
    Income: 60,
    Visitors: 63,
    CompletedOrders: 103,
    PendingOrders: 144,
    month: "June",
  },
  {
    Income: 59,
    Visitors: 60,
    CompletedOrders: 105,
    PendingOrders: 319,
    month: "July",
  },
  {
    Income: 65,
    Visitors: 60,
    CompletedOrders: 106,
    PendingOrders: 249,
    month: "Aug",
  },
  {
    Income: 51,
    Visitors: 51,
    CompletedOrders: 95,
    PendingOrders: 131,
    month: "Sept",
  },
  {
    Income: 60,
    Visitors: 65,
    CompletedOrders: 97,
    PendingOrders: 55,
    month: "Oct",
  },
  {
    Income: 67,
    Visitors: 64,
    CompletedOrders: 76,
    PendingOrders: 48,
    month: "Nov",
  },
  {
    Income: 61,
    Visitors: 70,
    CompletedOrders: 103,
    PendingOrders: 25,
    month: "Dec",
  },
];
export default SalesChartData;
