const ProductsData = [
  {
    id: 1,
    ProductName: "Iphone 15 Pro Max",
    Price: "1400 $",
    Stock: 14,
    Category: " New Mobile",
  },
  {
    id: 2,
    ProductName: "Iphone 14 Pro Max",
    Price: "1300 $",
    Stock: 31,
    Category: "New Mobile",
  },
  {
    id: 3,
    ProductName: "Iphone 13 Pro Max",
    Price: "1200 $",
    Stock: 31,
    Category: "New Mobile",
  },
  {
    id: 4,
    ProductName: "Iphone 12 Pro Max",
    Price: "1100 $",
    Stock: 11,
    Category: "New Mobile",
  },
  {
    id: 5,
    ProductName: "Iphone 11 Pro Max",
    Price: "1000 $",
    Stock: 25,
    Category: "Old Mobile",
  },
  {
    id: 6,
    ProductName: "Iphone xs Max",
    Price: "1000 $",
    Stock: 150,
    Category: "Old Mobile",
  },
  {
    id: 7,
    ProductName: "Iphone x Max",
    Price: "900 $",
    Stock: 44,
    Category: "Old Mobile",
  },
  {
    id: 8,
    ProductName: "Iphone 8 Plus",
    Price: "800 $",
    Stock: 36,
    Category: "Old Mobile",
  },
  {
    id: 9,
    ProductName: "Iphone 7 Plus",
    Price: "700 $",
    Stock: 65,
    Category: "Old Mobile",
  },
];
export default ProductsData;
